version: '3.9'

services:
  db:
    image: postgres
    volumes:
      - db-volume:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    restart: always
    ports:
      - "5433:5432"
  spring-backend:
    build: ./spring-backend/
    ports: 
      - ${SPRING_EXPOSED_PORT}:${SPRING_EXPOSED_PORT}
    depends_on:
      - "db"
    environment:
      TWILIO_ACCOUNT_SID: ${TWILIO_ACCOUNT_SID}
      TWILIO_AUTH_TOKEN: ${TWILIO_AUTH_TOKEN}
      TWILIO_PHONE_NUMBER: ${TWILIO_PHONE_NUMBER}
      SENDGRID_API_KEY: ${SENDGRID_API_KEY}
      SENDGRID_EMAIL_ADDRESS: ${SENDGRID_EMAIL_ADDRESS}
      ACCELEROMETER_CRASH_THRESHOLD: ${ACCELEROMETER_CRASH_THRESHOLD}
      DB_URL: ${DB_URL}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      PORT: ${SPRING_EXPOSED_PORT}
  react-frontend:
    build: ./react-frontend/
    ports:
      - "3000:3000"
    depends_on:
      - "db"
      - "spring-backend"

volumes:
  db-volume: