version: '3.9'

services:
  db:
    image: postgres
    volumes:
      - db-volume:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    restart: always
    ports:
      - "5433:5432"
  spring-backend:
    build: ./spring-backend/
    ports: 
      - "8080:8080"
    depends_on:
      - "db"
    environment:
      TWILIO_ACCOUNT_SID: ${TWILIO_ACCOUNT_SID}
      TWILIO_AUTH_TOKEN: ${TWILIO_AUTH_TOKEN}
      TWILIO_PHONE_NUMBER: ${TWILIO_PHONE_NUMBER}
      SENDGRID_API_KEY: ${SENDGRID_API_KEY}
      SENDGRID_EMAIL_ADDRESS: ${SENDGRID_EMAIL_ADDRESS}
      ACCELEROMETER_CRASH_THRESHOLD: ${ACCELEROMETER_CRASH_THRESHOLD}
      DB_NAME: ${DB_NAME}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
  react-frontend:
    build: ./react-frontend/
    ports:
      - "3000:3000"
    depends_on:
      - "db"
      - "spring-backend"
  liquibase:
    image: liquibase/liquibase
    container_name: liquibase
    depends_on:
      - "db"
    volumes:
      - ./liquibase/changelog.xml:/liquibase/changelog.xml
      - ./liquibase/sql-files/:/liquibase/sql-files/
    command: [
        '--url=jdbc:postgresql://db:5432/${DB_NAME}',
        '--changelog-file=changelog.xml',
        '--username=${DB_USERNAME}',
        '--password=${DB_PASSWORD}',
        'update'
        ]

volumes:
  db-volume: