server:
  port: ${PORT}
  servlet.session.cookie.name: DWM-SESSION

security:
  user:
    name: ${SPRING_ADMIN_USER_NAME}
    password: ${SPRING_ADMIN_USER_PASSWORD}

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa.hibernate.ddl-auto: validate
  liquibase:
    change-log: classpath:db/changelog.xml