server:
  port: ${PORT}

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa.hibernate.ddl-auto: validate
  liquibase:
    change-log: classpath:db/changelog.xml